import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import AsyncStorage from '@react-native-async-storage/async-storage';

const resources = {
  fr: {
    translation: {
      // ----------- Boutique / Shop -----------
      shop: {
        title: 'Boutique',
        subtitle: 'Ornements et fonctionnalités pour enrichir vos souffles',
        item_popular: 'Populaire',
        item_includes: "Inclus dans l'article",
        sections_backgrounds: 'Fonds premium',
        sections_tickets: 'Tickets et crédits',
        ethics_title: "Notre éthique",
        ethics_text: "Aucune incitation, pas d’abonnement, achats éthiques uniquement pour enrichir votre expérience.",
        legal_title: "Informations légales",
        legal_text: "Les achats sont valables uniquement sur cet appareil. Aucune donnée n’est revendue.",
        login_prompt_title: "Créer un compte pour acheter",
        login_prompt_text: "Connectez-vous pour profiter des achats premium.",
        login_prompt_button: "Créer un compte",
        item_button_buy: "Acheter pour {{price}}",
        item_button_offer: "Offrir pour {{price}}",
        item_button_processing: "Achat en cours...",
        item_alert_account_required_title: "Compte requis",
        item_alert_account_required_text: "Vous devez être connecté pour acheter cet article.",
        item_alert_account_required_cta: "Créer un compte",
        item_alert_thanks_title: "Merci !",
        item_alert_thanks_text: "Vous venez d’offrir un cadeau à la communauté.",
        item_alert_thanks_cta: "Fermer",
        item_alert_purchase_success_title: "Achat réussi",
        item_alert_purchase_success_text: "L’article a bien été ajouté à votre inventaire.",
        item_alert_purchase_success_cta: "Continuer",
        item_alert_error_title: "Erreur",
        item_alert_error_text: "Impossible de finaliser l’achat. Réessayez plus tard.",
        items: {
          ticket_pack_5: {
            name: "Pack de 5 tickets",
            description: "Débloquez 5 révélations à distance.",
            benefit1: "Révélez des souffles éloignés",
            benefit2: "Utilisable n’importe où",
            benefit3: "Sans expiration",
          },
          suspended_ticket: {
            name: "Ticket suspendu",
            description: "Offrez un ticket à la communauté.",
            benefit1: "Donnez un ticket au hasard",
            benefit2: "Fait apparaître un cadeau sur la carte",
            benefit3: "Renforce l’esprit collectif",
            benefit4: "Crée du lien local",
          },
          background_mist: {
            name: "Brume mystique",
            description: "Un voile éthéré pour vos souffles.",
            benefit1: "Design exclusif",
            benefit2: "Valorise vos souffles",
            benefit3: "Éphémère et poétique",
          },
          background_sunray: {
            name: "Rayons de soleil",
            description: "Illuminez vos messages avec une aura dorée.",
            benefit1: "Apparence lumineuse",
            benefit2: "Effet unique sur la carte",
            benefit3: "Réservé aux explorateurs",
          },
          background_autumn: {
            name: "Feuilles d’automne",
            description: "Pour des souffles aux couleurs chaleureuses.",
            benefit1: "Décor saisonnier",
            benefit2: "Idéal pour messages doux",
            benefit3: "Limité dans le temps",
          },
        },
      },

      // ----------- Navigation & Tabs -----------
      tabs: {
        map: 'Carte',
        dashboard: 'Tableau de bord',
        moderation: 'Modération',
        about: 'À propos',
        settings: 'Paramètres',
      },

      // ----------- Main Map Screen -----------
      title: 'Silagora',
      subtitle: '"Un message déposé en ce lieu ne pourra être lu que par ceux qui fouleront ce même sol"',
      activeSouffles_one: '{{count}} souffle actif',
      activeSouffles_other: '{{count}} souffles actifs',
      read: 'contempler',
      write: 'composer',
      locating: 'Recherche de votre position...',
      locationRequired: 'Position requise',
      locationRequiredToExplore: 'Position requise pour explorer',
      locationRequiredForDeposit: 'Votre position est nécessaire pour déposer un souffle. Voulez-vous activer la localisation ?',
      approachAura: 'Approchez-vous d\'un halo pour révéler un souffle...',
      chooseLocation: 'Choisissez un lieu pour y déposer votre trace...',
      retry: 'Réessayer',
      later: 'Plus tard',
      activate: 'Activer',
      tooFar: 'Trop loin',
      tooFarDescription: 'Vous devez vous approcher à moins de 15 mètres pour révéler ce souffle.',
      loadingMap: 'Préparation de la carte aquarelle...',
      clearSimulatedSoufflesTitle: 'Nettoyer la carte ?',
      clearSimulatedSoufflesMessage: 'Cette action va supprimer tous les souffles simulés de la carte. Vos propres souffles ne seront pas affectés. Continuer ?',
      clear: 'Nettoyer',
      mapCleared: 'Carte nettoyée',
      mapClearedMessage: 'Les souffles simulés ont été effacés.',
      
      souffleRevealedTitle: 'Souffle révélé ! ✨',
      souffleRevealedMessage: 'Un nouveau message s\'épanouit sous vos pas...',
      prepareContemplativeSpace: 'Préparation de votre espace contemplatif',
      locationFound: 'Position trouvée !',
      spaceReady: 'Votre espace est prêt',
      locationErrorTitle: 'Erreur de localisation',
      locationErrorMessage: 'Impossible d\'obtenir votre position',
      processing: 'Traitement...',
      preparingPurchase: 'Préparation de votre achat',
      purchaseSuccess: 'Achat réussi !',
      newOrnamentsAvailable: 'Vos nouveaux ornements sont disponibles',
      purchaseErrorTitle: 'Erreur d\'achat',
      purchaseErrorMessage: 'Impossible de finaliser la transaction',
      cancel: 'Annuler',
      justNow: 'à l\'instant',
      minutesAgo: 'il y a {{count}} min',
      hoursAgo: 'il y a {{count}}h',
      souffleRevealed: 'Souffle révélé',
      locationPermissionDeniedTitle: 'Permission de localisation refusée',
      locationPermissionDeniedMessage: 'La permission de localisation est refusée en permanence. Veuillez l\'activer manuellement dans les paramètres de votre appareil.',
      openSettings: 'Ouvrir les paramètres',

      // ----------- Souffle Modal (composer un souffle) -----------
      depositBreath: 'Composer un souffle',
      leaveYourTrace: 'Laissez votre trace en ce lieu',
      anonymousMode: 'Mode anonyme',
      anonymousDepositText: 'Votre souffle sera déposé de manière anonyme. Il flottera librement, sans être lié à une identité.',
      breathPlaceholder: 'Que souhaitez-vous murmurer à ce lieu ?',
      charactersRemaining_one: '{{count}} caractère restant',
      charactersRemaining_other: '{{count}} caractères restants',
      chosenOrnament: 'Ornement choisi :',
      addSticker: 'Ajouter un ornement',
      hideStickers: 'Masquer les ornements',
      emotionsCategory: 'Émotions',
      natureCategory: 'Nature',
      objectsCategory: 'Objets',
      symbolsCategory: 'Symboles',
      premiumOrnamentsNote: '✨ Trouvez des tickets suspendus sur la carte pour débloquer les ornements premium !',
      breathDuration: 'Durée de vie du souffle',
      hours24: '24 heures',
      hours48: '48 heures',
      locationAnchorText: 'Votre souffle sera ancré à ce lieu précis, comme une empreinte invisible',
      poeticQuoteSouffle: 'Un souffle déposé ici ne pourra être révélé que par ceux qui fouleront ce même sol, créant une rencontre fortuite entre âmes errantes.',
      depositHere: 'Déposer délicatement',
      depositing: 'Dépôt en cours...',
      breathDeposited: 'Souffle déposé',
      breathDepositedMessage: 'Votre souffle a été délicatement déposé en ce lieu. Il flottera maintenant dans l\'attente d\'être découvert.',

      // ----------- Dashboard -----------
      dashboard: {
        title: 'Tableau de bord',
        subtitle: 'Vos statistiques personnelles',
        welcome: 'Bonjour, {{pseudo}} 🌸',
        anonymous: {
          title: 'Créez un compte pour voir vos statistiques',
          text: 'Découvrez votre empreinte poétique sur le territoire, vos achievements et votre progression.',
        },
        stats: {
          created: 'Souffles créés',
          createdSubtitle: 'Vos traces déposées',
          revealed: 'Souffles révélés',
          revealedSubtitle: 'Découvertes faites',
          distance: 'Distance parcourue',
          distanceSubtitle: 'En explorant',
          activeDays: 'Jours actifs',
          activeDaysSubtitle: 'Depuis le début',
        },
        emotion: {
          title: 'Votre émotion signature',
          subtitle: 'L\'émotion que vous exprimez le plus souvent',
        },
        weeklyActivity: {
          title: 'Activité de la semaine',
        },
        achievements: {
          title: 'Achievements',
          subtitle: 'Débloquez des récompenses en explorant Silagora',
          achievementUnlocked: 'Débloqué',
        },
        advancedStats: {
          title: 'Statistiques avancées',
          streak: 'Plus longue série',
          streakUnit_one: '{{count}} jour',
          streakUnit_other: '{{count}} jours',
          places: 'Lieux visités',
          achievementsCount: 'Achievements',
        },
      },

      // ----------- Emotions -----------
      emotions: {
        joyeux: 'Joyeux(se)',
        triste: 'Triste',
        colere: 'En colère',
        anxieux: 'Anxieux(se)',
        aimant: 'Aimant(e)',
        fatigue: 'Fatigué(e)',
        detendu: 'Détendu(e)',
        pensif: 'Pensif(ve)',
        bouleverse: 'Bouleversé(e)',
        apaise: 'Apaisé(e)',
        perdu: 'Perdu(e)',
        ironique: 'Ironique',
        silencieux: 'Silencieux(se)',
        emu: 'Ému(e)',
        honteux: 'Honteux(se)',
      },

      // ----------- Moderation -----------
      moderation: {
        title: 'Modération Citoyenne',
        subtitle: 'Contribuez à un espace bienveillant',
        approveTitle: 'Approuver ce souffle ?',
        approveMessage: 'Voulez-vous vraiment approuver ce souffle ? Il sera alors visible par tous les utilisateurs.',
        approveConfirm: 'Approuver',
        approvedConfirmation: 'Souffle approuvé et rendu visible.',
        rejectTitle: 'Rejeter ce souffle ?',
        rejectMessage: 'Voulez-vous vraiment rejeter ce souffle ? Il sera définitivement masqué et supprimé de la carte.',
        rejectConfirm: 'Rejeter',
        rejectedConfirmation: 'Souffle rejeté et masqué.',
        notAuthorizedTitle: 'Accès non autorisé',
        notAuthorizedText: 'La modération est réservée aux utilisateurs avec un compte premium.',
        emptyQueue: 'File de modération vide',
        emptyQueueSubtext: 'Aucun souffle signalé en attente de révision pour le moment. Tout est calme !',
        refresh: 'Rafraîchir',
        souffleId: 'ID du souffle',
        approve: 'Approuver',
        reject: 'Rejeter',
      },

      // ----------- Settings -----------
      settings: {
        audio: {
          title: "Expérience Audio Immersive",
          subtitle: "Sons adaptatifs, spatiaux et contextuels pour une immersion totale",
          enable: "Activer l'expérience audio",
          volume: "Volume principal",
          theme: "Univers sonore",
          immersiveFeatures: "Fonctionnalités immersives",
          spatial: "Audio spatial",
          adaptive: "Volume adaptatif",
          contextual: "Sons contextuels",
          statusActive: "Expérience immersive active",
          statusPaused: "Ambiance en pause",
          description: "L'expérience audio immersive s'adapte automatiquement à vos actions : sons de proximité quand vous approchez d'un souffle, ambiance douce pendant la composition, effets spatiaux dans les lieux d'écho.",
        },
        personalizeJourney: 'Personnalisez votre voyage contemplatif',
        appLanguage: 'Langue de l\'application',
        languageSubtitle: 'La langue dans laquelle souffle votre monde',
        languageDefault: 'Français (par défaut)',
        visualMode: 'Mode visuel',
        visualSubtitle: 'Votre regard est-il fait de lumière ou d\'encre noire ?',
        enableNightMode: 'Activer le mode nuit',
        adaptToDaylight: 'Adapter au cycle du jour',
        visualModeNote: '🌙 Le mode visuel sera appliqué lors du prochain redémarrage de l\'application',
        breathRadius: 'Rayon de souffle',
        radiusSubtitle: 'À quelle distance voulez-vous que le vent vous écoute ?',
        privacy: 'Confidentialité & modération',
        privacySubtitle: 'Un espace sûr pour que chaque souffle puisse s\'épanouir',
        hideExactLocation: 'Cacher ma position exacte',
        moderatedReading: 'Lecture modérée des souffles sensibles',
        participateModeration: 'Participer à la modération citoyenne',
        notifications: 'Notifications',
        notificationsSubtitle: 'Faut-il qu\'un écho vous prévienne ?',
        notifyWhenRead: 'M\'avertir quand un souffle est lu',
        notifyNearby: 'M\'avertir des nouveaux souffles proches',
        onlyWhenMoving: 'Seulement si je suis en déplacement',
        personalHistory: 'Historique personnel',
        historySubtitle: 'Les traces que vous choisissez de garder',
        saveDrafts: 'Conserver les brouillons non déposés',
        keepHistory: 'Voir les lieux où j\'ai soufflé (7 jours)',
        clearTraces: 'Effacer mes traces',
        aboutUs: 'À propos',
        aboutSubtitle: 'Qui sommes-nous ? Pourquoi ce vent ?',
        readManifesto: 'Lire le manifeste',
        openSource: 'Projet open-source',
        contactModeration: 'Contact & modération',
        version: 'Version {{version}}',
        resetPreferences: 'Effacer les préférences locales',
        account: 'Compte',
        accountInfo: 'Informations de votre compte',
        createAccountPrompt: 'Créez un compte pour sauvegarder vos préférences',
        contact: 'Contact :',
        pseudo: 'Pseudo :',
        memberSince: 'Membre depuis :',
        logout: 'Se déconnecter',
        logoutConfirm: 'Êtes-vous sûr de vouloir vous déconnecter ?',
        createAccount: 'Créer un compte',
        alreadyHaveAccount: 'J\'ai déjà un compte',
        anonymousText: 'Vous utilisez Silagora en mode contemplatif anonyme. Créez un compte pour :',
        anonymousFeature1: '• Sauvegarder vos préférences',
        anonymousFeature2: '• Synchroniser entre appareils',
        anonymousFeature3: '• Accéder aux ornements premium',
        anonymousFeature4: '• Participer à la modération bienveillante',
        discoverShop: 'Découvrir la boutique',
        resetSettingsTitle: 'Repartir d\'une page blanche',
        resetSettingsMessage: 'Cela effacera tous vos paramètres et préférences. Cette action est irréversible.',
        settingsCleared: 'Paramètres effacés',
        settingsClearedMessage: 'Tous vos paramètres ont été remis à zéro.',
        clearTracesTitle: 'Effacer mes traces',
        clearTracesMessage: 'Cela supprimera définitivement tous vos souffles et votre historique local.',
        tracesCleared: 'Traces effacées',
        tracesClearedMessage: 'Votre historique local a été supprimé.',
        citizenModerationTitle: 'Modération citoyenne',
        citizenModerationIntro: 'La modération citoyenne permet à la communauté de maintenir un espace bienveillant et respectueux.',
        howItWorksColon: 'Comment ça fonctionne :',
        moderationPoint1: '• Chaque membre authentifié peut signaler un souffle jugé inapproprié.',
        moderationPoint2: '• Le souffle signalé est temporairement masqué et soumis à l\'IA pour une première analyse.',
        moderationPoint3: '• Si l\'IA confirme un problème, le souffle est soumis à une revue par un panel de modérateurs citoyens.',
        moderationPoint4: '• Un souffle est définitivement masqué après un certain nombre de signalements ou la validation par des modérateurs.',
        moderationCriteriaColon: 'Critères de modération :',
        criteriaPoint1: '• Pas de contenu haineux, discriminatoire ou violent.',
        criteriaPoint2: '• Pas de harcèlement, d\'intimidation ou de menaces.',
        criteriaPoint3: '• Pas de contenu publicitaire, spam ou promotionnel.',
        criteriaPoint4: '• Pas de divulgation d\'informations personnelles (téléphone, email, adresse, etc.).',
        moderationParticipationNote: 'Votre participation est volontaire et contribue à un espace plus sûr pour tous.',
        understood: 'Compris',
        shop: 'Boutique',
      },

      // ----------- About -----------
      about: {
        title: 'À propos de Silagora',
        etymology: 'du latin "silere" (se taire) et du grec "agora" (place publique)',
        description: "Une carte sensible de l'expression humaine anonyme, libre et géolocalisée.",
        philosophy: {
          title: 'Notre philosophie',
          text1: "Dans un monde saturé de bruit numérique, Silagora offre un espace de silence et de contemplation. Chaque souffle déposé est une trace éphémère, un murmure dans l'espace et le temps.",
          text2: "Nous croyons en la beauté de l'anonymat, en la poésie du temporaire, et en la magie des rencontres fortuites.",
        },
        howItWorks: {
          title: 'Comment ça marche',
          step1: { title: 'Composer un souffle', text: 'Écrivez un message court (280 caractères max) et déposez-le délicatement à votre position actuelle. Ajoutez un ornement pour enrichir votre expression.' },
          step2: { title: 'Explorer la carte aquarelle', text: 'Découvrez les halos translucides qui flottent autour de vous. Chaque bulle cache un souffle déposé par un autre voyageur.' },
          step3: { title: 'Révéler les souffles', text: "Approchez-vous physiquement d'un halo (dans un rayon de 15 mètres) pour révéler le message qu'il contient." },
        },
        ephemeral: {
          title: "L'art de l'éphémère",
          text1: 'Chaque souffle a une durée de vie limitée : 24 ou 48 heures. Passé ce délai, il s\'évapore naturellement, laissant place à de nouveaux murmures.',
          text2: 'Cette temporalité encourage la spontanéité et préserve la fraîcheur de chaque découverte.',
        },
        echoPlaces: {
          title: "Les Lieux d'Écho",
          text: "Quand plusieurs souffles se croisent en un même lieu, naît un Lieu d'Écho. Ces espaces particuliers deviennent des carrefours poétiques où les voix se mêlent.",
        },
        ethics: {
          title: 'Notre éthique',
          point1: '• Anonymat total : aucun profil, aucun suivi',
          point1Short: 'Anonymat total',
          point2: '• Pas de likes, partages ou statistiques',
          point3: '• Modération communautaire bienveillante',
          point4: '• Respect de la vie privée et des données',
          point5: '• Sobriété numérique et design contemplatif',
          point5Short: 'Sobriété numérique',
        },
        contact: {
          title: 'Nous contacter',
          email: 'contact@silagora.app',
          openSource: 'Projet open-source',
        },
        quote: {
          text: '"Dans le silence de l\'agora numérique, chaque souffle devient une étoile éphémère qui guide les âmes errantes vers des rencontres inattendues."',
          author: 'L\'équipe Silagora',
        },
        version: 'Version {{version}}',
        hackathonCredit: 'Fait avec 💙 pour le Hackathon Bolt • Juin 2025',
      },

      // SECTION COMMUNE AJOUTÉE
      common: {
        tooFarToRevealTitle: "Trop Loin pour Révéler",
        tooFarToRevealMessage: "Vous êtes à {{distance}}m. Pour révéler ce souffle, vous devez être plus proche ou utiliser un de vos {{ticketCount}} tickets.",
        useOneTicket: "Utiliser 1 ticket",
        cancel: "Annuler",
        souffleRevealed: "Souffle Révélé !",
        ticketsRemaining_one: "Il vous reste {{count}} ticket.",
        ticketsRemaining_other: "Il vous reste {{count}} tickets.",
        ticketsExhausted: "Plus de tickets",
        visitShopForMoreTickets: "Visitez la boutique pour obtenir plus de tickets.",
        functionalityReserved: "Fonctionnalité réservée",
        accountRequiredForDistantReveal: "La révélation à distance requiert un compte pour gérer vos tickets."
      },

      // ----------- Achievements -----------
      achievements: {
        first_souffle: {
          title: 'Premier Souffle',
          description: 'Déposer votre premier souffle',
        },
        explorer: {
          title: 'Explorateur',
          description: 'Révéler 10 souffles',
        },
        poet: {
          title: 'Poète Urbain',
          description: 'Créer 25 souffles',
        },
        wanderer: {
          title: 'Vagabond',
          description: 'Parcourir 10 km en explorant',
        },
        consistent: {
          title: 'Régulier',
          description: 'Utiliser Silagora 7 jours consécutifs',
        },
        social: {
          title: 'Connecteur',
          description: 'Révéler des souffles dans 5 lieux différents',
        },
      },

      // ----------- Master Login -----------
      masterLogin: {
        title: 'Accès Maître',
        subtitle: 'Zone réservée aux développeurs',
        error: {
          emptyCode: 'Veuillez entrer le code maître.',
          incorrectCode: 'Code maître incorrect. Accès non autorisé.',
          creationFailed: 'Échec de la création du compte maître.',
        },
        success: {
          title: 'Accès Maître accordé',
          message: 'Bienvenue, Développeur ! Votre compte maître a été activé avec tous les privilèges.',
        },
        instructions: {
          title: 'Authentification Développeur',
          text: 'Veuillez entrer le code maître fourni pour accéder aux fonctionnalités de développement avancées.',
          hint: 'Pour la démo du hackathon, le code est "DEMO2024".',
        },
        input: {
          label: 'Code Maître',
          placeholder: 'Entrez le code ici',
        },
        benefits: {
          title: 'Avantages du compte maître',
          item1: '✨ Accès illimité aux ornements premium',
          item2: '🎫 Tickets de révélation illimités',
          item3: '🛡️ Outils de modération avancés',
          item4: '🔧 Accès aux fonctionnalités de débogage',
        },
        security: {
          title: 'Note de sécurité',
          text: 'Cet accès est uniquement pour les besoins de développement. Ne partagez jamais le code maître en production.',
        },
        button: {
          loading: 'Connexion...',
          text: 'Se connecter en tant que Maître',
        },
      },
      
      // ----------- Complete Profile -----------
      completeProfileTitle: 'Finaliser le profil',
      completeProfileSubtitle: 'Dernière étape avant l\'envol',
      error: 'Erreur',
      pseudoTooShort: 'Le pseudo doit contenir au moins 2 caractères.',
      profileCompletedTitle: 'Profil finalisé !',
      profileCompletedMessage: 'Votre profil est maintenant complet. Vous êtes prêt(e) à vous envoler !',
      start: 'Commencer',
      unexpectedError: 'Une erreur inattendue est survenue.',
      skipStepTitle: 'Passer cette étape ?',
      skipStepMessage: 'Vous pouvez finaliser votre pseudo plus tard dans les paramètres. Souhaitez-vous continuer sans pseudo ?',
      stayHere: 'Rester ici',
      skip: 'Passer',
      welcomeTitleCompleteProfile: 'Félicitations ! 🌸',
      welcomeTextCompleteProfile: 'Votre compte a été créé avec succès. Il ne reste plus qu\'une petite touche pour personnaliser votre expérience.',
      yourAccount: 'Votre compte',
      contactLabel: 'Contact :',
      typeLabel: 'Type :',
      emailType: 'Email',
      phoneType: 'Téléphone',
      choosePseudoTitle: 'Choisissez votre pseudo',
      pseudoDescription: 'Votre pseudo est la seule "identité" visible. Choisissez-le avec soin, ou laissez-le vide pour plus d\'anonymat.',
      pseudoPlaceholder: 'Votre pseudo (facultatif)',
      pseudoHint: 'Max 20 caractères. Modifiable plus tard dans les paramètres.',
      accountBenefitsTitle: 'Avec votre compte, vous pouvez :',
      benefitSaveSync: 'Sauvegarder et synchroniser vos préférences sur tous vos appareils.',
      benefitPremiumFeatures: 'Accéder à des ornements de souffle premium exclusifs.',
      benefitOfferTickets: 'Offrir des "tickets suspendus" pour soutenir la communauté.',
      benefitModeration: 'Participer à la modération citoyenne pour un espace bienveillant.',
      ourPromise: 'Notre promesse',
      ethicsReminderText: 'Nous nous engageons à protéger votre vie privée et à ne jamais partager vos données personnelles.',
      finalizingProfile: 'Finalisation...',
      completeProfileButton: 'Finaliser le profil',
      skipStepButton: 'Passer cette étape',

      // ----------- Create Account -----------
      createAccount: {
        title: 'Créer un compte',
        subtitle: 'Une nouvelle page s\'ouvre...',
        howToConnect: 'Comment souhaitez-vous vous connecter ?',
        emailLabel: 'Votre adresse email',
        phoneLabel: 'Votre numéro de téléphone',
        emailPlaceholder: 'exemple@domaine.com',
        phonePlaceholder: '+33612345678',
        pseudoLabel: 'Votre pseudo (facultatif)',
        pseudoHint: 'Si laissé vide, vous resterez entièrement anonyme. Vous pourrez en choisir un plus tard.',
        pseudoPlaceholder: 'Votre pseudo',
        authTitle: 'Comment fonctionne l\'authentification ?',
        authText: 'Nous vous enverrons un code à usage unique par {{contactType}} pour vérifier votre identité. Pas de mot de passe, c\'est plus simple et plus sécurisé.',
        authBenefits: 'Cela nous permet de protéger votre compte et de synchroniser vos données sans jamais stocker de mot de passe.',
        commitmentTitle: 'Notre engagement',
        commitment1: '🔒 Sécurité des données : Vos informations sont chiffrées et protégées.',
        commitment2: '👤 Anonymat garanti : Vos souffles ne sont pas liés à votre identité réelle.',
        commitment3: '🌱 Sobriété numérique : Pas de pub, pas d\'algorithme manipulateur.',
        submitButton: 'Créer mon compte',
        submitButtonLoading: 'Création en cours...',
        terms: 'En créant un compte, vous acceptez nos Conditions Générales d\'Utilisation et notre Politique de Confidentialité.',
        errorContactRequired: 'Veuillez entrer une adresse email ou un numéro de téléphone.',
      },

      // ----------- Login -----------
      login: {
        title: 'Connexion',
        subtitle: 'Le retour de l\'écho...',
        welcomeBack: 'Heureux de vous revoir !',
        instructions: 'Veuillez entrer votre contact pour recevoir un code de connexion.',
        connectionMethod: 'Comment souhaitez-vous vous connecter ?',
        emailLabel: 'Votre adresse email',
        phoneLabel: 'Votre numéro de téléphone',
        emailPlaceholder: 'exemple@domaine.com',
        phonePlaceholder: '+33612345678',
        howItWorks: 'Comment ça marche ?',
        step1: '1. Vous entrez votre adresse {{contactType}}.',
        phone_number_text: 'numéro de téléphone',
        step2: '2. Nous vous envoyons un code à usage unique par email ou SMS.',
        step3: '3. Vous entrez ce code pour vous connecter instantanément.',
        needHelp: 'Besoin d\'aide ?',
        helpText: 'Si vous n\'avez pas encore de compte ou si vous rencontrez des problèmes de connexion, vous pouvez en créer un nouveau.',
        createNewAccount: 'Créer un nouveau compte',
        submitButton: 'Recevoir mon code',
        submitButtonLoading: 'Envoi du code...',
        errorContactRequired: 'Veuillez entrer une adresse email ou un numéro de téléphone.',
      },

      // ----------- Verify OTP -----------
      verifyOtp: {
        title: 'Vérification',
        subtitle: 'Le murmure de l\'authentification',
        codeSentTitle: 'Code envoyé !',
        codeSentTo: 'Nous avons envoyé un code de vérification à :',
        expiresIn: 'Il expire dans {{count}} minute(s).',
        errorIncomplete: 'Veuillez entrer le code complet à 6 chiffres.',
        errorTitle: 'Code incorrect',
        errorMessage: 'Le code que vous avez entré est incorrect ou a expiré.',
        attemptsRemaining: '{{count}} tentative(s) restante(s).',
        resendCode: 'Renvoyer le code',
        resendCodeWait: 'Renvoyer dans {{count}}s',
        resendTitle: 'Code renvoyé',
        resendMessage: 'Un nouveau code a été envoyé.',
        resendError: 'Impossible de renvoyer le code. Réessayez plus tard.',
        tipsTitle: 'Conseils :',
        tips: '• Vérifiez vos spams. • Assurez-vous que votre numéro/email est correct. • Contactez le support si le problème persiste.',
        submitButton: 'Vérifier le code',
        submitButtonLoading: 'Vérification...',
      },
      
      // ----------- Welcome (First Launch) -----------
      welcome: {
        feature1: { title: 'Souffles éphémères', description: 'Déposez des messages qui s\'évaporent naturellement.' },
        feature2: { title: 'Géolocalisation poétique', description: 'Chaque souffle est ancré à un lieu précis.' },
        feature3: { title: 'Anonymat bienveillant', description: 'Pas de profil, pas de followers, juste l\'essentiel.' },
        feature4: { title: 'Rencontres fortuites', description: 'Découvrez les traces laissées par d\'autres voyageurs.' },
        featuresTitle: 'L\'art du souffle numérique',
        ethics3Text: 'Pas de publicité',
        ethics4Text: 'Open source',
        startButton: 'Commencer l\'aventure',
        alreadyAccountButton: 'J\'ai déjà un compte',
        developerAccess: 'Accès développeur',
        locationModalTitle: 'Activer la localisation ?',
        locationModalText: 'Silagora a besoin de votre position pour vous permettre de déposer et découvrir des souffles autour de vous. Votre position exacte ne sera jamais enregistrée ni partagée.',
        locationModalButton: 'Oui, activer la localisation',
        locationModalSkip: 'Continuer sans localisation',
        locationSuccessTitle: 'Localisation activée !',
        locationSuccessMessage: 'Vous êtes prêt(e) à explorer le monde des souffles.',
        locationDeniedTitle: 'Localisation désactivée',
        locationDeniedMessage: 'Certaines fonctionnalités seront limitées sans votre position. Vous pourrez l\'activer plus tard dans les paramètres de votre appareil.',
        audioModalTitle: 'Activer l\'expérience audio ?',
        audioModalText: 'L\'audio immersif enrichit votre exploration avec des ambiances sonores contextuelles et des effets spatiaux. Une immersion poétique sans casque, autour de vous.',
        audioModalButton: 'Oui, activer l\'audio',
        audioModalSkip: 'Continuer sans le son',
        audioSuccessTitle: 'Audio activé !',
        audioSuccessMessage: 'Plongez dans l\'univers sonore de Silagora.',
        audioDeniedTitle: 'Audio désactivé',
        audioDeniedMessage: 'L\'expérience sera moins immersive sans l\'audio. Vous pourrez l\'activer à tout moment dans les paramètres.',
      },
    },
  },
  en: {
    translation: {
      // ----------- Shop -----------
      shop: {
        title: 'Shop',
        subtitle: 'Ornaments and features to enrich your breaths',
        item_popular: 'Popular',
        item_includes: "Included in this item",
        sections_backgrounds: 'Premium backgrounds',
        sections_tickets: 'Tickets and credits',
        ethics_title: "Our ethics",
        ethics_text: "No subscription, no pressure—purchases only to enhance your experience.",
        legal_title: "Legal information",
        legal_text: "Purchases are valid only on this device. No data is resold.",
        login_prompt_title: "Create an account to buy",
        login_prompt_text: "Log in to enjoy premium purchases.",
        login_prompt_button: "Create account",
        item_button_buy: "Buy for {{price}}",
        item_button_offer: "Gift for {{price}}",
        item_button_processing: "Processing...",
        item_alert_account_required_title: "Account required",
        item_alert_account_required_text: "You must be logged in to buy this item.",
        item_alert_account_required_cta: "Create account",
        item_alert_thanks_title: "Thank you!",
        item_alert_thanks_text: "You’ve just gifted something to the community.",
        item_alert_thanks_cta: "Close",
        item_alert_purchase_success_title: "Purchase successful",
        item_alert_purchase_success_text: "The item has been added to your inventory.",
        item_alert_purchase_success_cta: "Continue",
        item_alert_error_title: "Error",
        item_alert_error_text: "Unable to complete purchase. Please try again later.",
        items: {
          ticket_pack_5: {
            name: "5 Ticket Pack",
            description: "Unlock 5 distant reveals.",
            benefit1: "Reveal faraway breaths",
            benefit2: "Usable anywhere",
            benefit3: "Never expires",
          },
          suspended_ticket: {
            name: "Suspended ticket",
            description: "Gift a ticket to the community.",
            benefit1: "Random gift to a stranger",
            benefit2: "Appears as a present on the map",
            benefit3: "Strengthens local connection",
            benefit4: "Fosters community spirit",
          },
          background_mist: {
            name: "Mystical mist",
            description: "A misty veil for your breaths.",
            benefit1: "Exclusive design",
            benefit2: "Highlights your breaths",
            benefit3: "Ephemeral and poetic",
          },
          background_sunray: {
            name: "Sunrays",
            description: "Shine your messages with golden light.",
            benefit1: "Bright appearance",
            benefit2: "Unique effect on the map",
            benefit3: "For seasoned explorers",
          },
          background_autumn: {
            name: "Autumn leaves",
            description: "For warm, colorful breaths.",
            benefit1: "Seasonal theme",
            benefit2: "Ideal for gentle messages",
            benefit3: "Limited time only",
          },
        },
      },

      // ----------- Navigation & Tabs -----------
      tabs: {
        map: 'Map',
        dashboard: 'Dashboard',
        moderation: 'Moderation',
        about: 'About',
        settings: 'Settings',
      },

      // ----------- Main Map Screen -----------
      title: 'Silagora',
      subtitle: '"A message left in this place can only be read by those who will walk this same ground"',
      activeSouffles_one: '{{count}} active breath',
      activeSouffles_other: '{{count}} active breaths',
      read: 'contemplate',
      write: 'compose',
      locating: 'Searching for your position...',
      locationRequired: 'Location required',
      locationRequiredToExplore: 'Location required to explore',
      locationRequiredForDeposit: 'Your position is necessary to deposit a breath. Do you want to enable location?',
      approachAura: 'Approach a halo to reveal a breath...',
      chooseLocation: 'Choose a place to leave your trace...',
      retry: 'Retry',
      later: 'Later',
      activate: 'Activate',
      tooFar: 'Too far',
      tooFarDescription: 'You must approach within 15 meters to reveal this breath.',
      loadingMap: 'Preparing the watercolor map...',
      clearSimulatedSoufflesTitle: 'Clear the map?',
      clearSimulatedSoufflesMessage: 'This action will remove all simulated breaths from the map. Your own breaths will not be affected. Continue?',
      clear: 'Clear',
      mapCleared: 'Map cleared',
      mapClearedMessage: 'The simulated breaths have been erased.',

      souffleRevealedTitle: 'Souffle Revealed! ✨',
      souffleRevealedMessage: 'A new message blossoms under your steps...',
      prepareContemplativeSpace: 'Preparing your contemplative space',
      locationFound: 'Location Found!',
      spaceReady: 'Your space is ready',
      locationErrorTitle: 'Location Error',
      locationErrorMessage: 'Unable to get your location',
      processing: 'Processing...',
      preparingPurchase: 'Preparing your purchase',
      purchaseSuccess: 'Purchase Successful!',
      newOrnamentsAvailable: 'Your new ornaments are available',
      purchaseErrorTitle: 'Purchase Error',
      purchaseErrorMessage: 'Unable to complete the transaction',
      cancel: 'Cancel',
      justNow: 'just now',
      minutesAgo: '{{count}} min ago',
      hoursAgo: '{{count}}h ago',
      souffleRevealed: 'Souffle Revealed',
      locationPermissionDeniedTitle: 'Location Permission Denied',
      locationPermissionDeniedMessage: 'Location permission is permanently denied. Please enable it manually in your device settings.',
      openSettings: 'Open Settings',

      // ----------- Souffle Modal (compose a breath) -----------
      depositBreath: 'Compose a breath',
      leaveYourTrace: 'Leave your trace in this place',
      anonymousMode: 'Anonymous mode',
      anonymousDepositText: 'Your breath will be deposited anonymously. It will float freely, without being linked to an identity.',
      breathPlaceholder: 'What would you like to whisper to this place?',
      charactersRemaining_one: '{{count}} character remaining',
      charactersRemaining_other: '{{count}} characters remaining',
      chosenOrnament: 'Chosen ornament:',
      addSticker: 'Add ornament',
      hideStickers: 'Hide ornaments',
      emotionsCategory: 'Emotions',
      natureCategory: 'Nature',
      objectsCategory: 'Objects',
      symbolsCategory: 'Symbols',
      premiumOrnamentsNote: '✨ Find suspended tickets on the map to unlock premium ornaments!',
      breathDuration: 'Breath lifespan',
      hours24: '24 hours',
      hours48: '48 hours',
      locationAnchorText: 'Your breath will be anchored to this precise location, like an invisible imprint',
      poeticQuoteSouffle: 'A breath deposited here can only be revealed by those who will tread this same ground, creating a serendipitous encounter between wandering souls.',
      depositHere: 'Deposit gently',
      depositing: 'Depositing...',
      breathDeposited: 'Breath deposited',
      breathDepositedMessage: 'Your breath has been gently deposited in this place. It will now float waiting to be discovered.',

      // ----------- Dashboard -----------
      dashboard: {
        title: 'Dashboard',
        subtitle: 'Your personal statistics',
        welcome: 'Hello, {{pseudo}} 🌸',
        anonymous: {
          title: 'Create an account to see your stats',
          text: 'Discover your poetic footprint on the map, your achievements, and your progress.',
        },
        stats: {
          created: 'Breaths Composed',
          createdSubtitle: 'Your traces left behind',
          revealed: 'Breaths Revealed',
          revealedSubtitle: 'Discoveries made',
          distance: 'Distance Walked',
          distanceSubtitle: 'While exploring',
          activeDays: 'Active Days',
          activeDaysSubtitle: 'Since the beginning',
        },
        emotion: {
          title: 'Your Signature Emotion',
          subtitle: 'The emotion you express most often',
        },
        weeklyActivity: {
          title: 'Weekly Activity',
        },
        achievements: {
          title: 'Achievements',
          subtitle: 'Unlock rewards by exploring Silagora',
          achievementUnlocked: 'Unlocked',
        },
        advancedStats: {
          title: 'Advanced Stats',
          streak: 'Longest Streak',
          streakUnit_one: '{{count}} day',
          streakUnit_other: '{{count}} days',
          places: 'Places Visited',
          achievementsCount: 'Achievements',
        },
      },

      // ----------- Emotions -----------
      emotions: {
        joyeux: 'Joyful',
        triste: 'Sad',
        colere: 'Angry',
        anxieux: 'Anxious',
        aimant: 'Loving',
        fatigue: 'Tired',
        detendu: 'Relaxed',
        pensif: 'Thoughtful',
        bouleverse: 'Upset',
        apaise: 'Calm',
        perdu: 'Lost',
        ironique: 'Ironic',
        silencieux: 'Silent',
        emu: 'Moved',
        honteux: 'Ashamed',
      },

      // ----------- Moderation -----------
      moderation: {
        title: 'Citizen Moderation',
        subtitle: 'Contribute to a benevolent space',
        approveTitle: 'Approve this breath?',
        approveMessage: 'Do you really want to approve this breath? It will then be visible to all users.',
        approveConfirm: 'Approve',
        approvedConfirmation: 'Breath approved and made visible.',
        rejectTitle: 'Reject this breath?',
        rejectMessage: 'Do you really want to reject this breath? It will be permanently hidden and removed from the map.',
        rejectConfirm: 'Reject',
        rejectedConfirmation: 'Breath rejected and hidden.',
        notAuthorizedTitle: 'Unauthorized Access',
        notAuthorizedText: 'Moderation is reserved for users with a premium account.',
        emptyQueue: 'Moderation queue is empty',
        emptyQueueSubtext: 'No flagged breaths awaiting review at the moment. All is calm!',
        refresh: 'Refresh',
        souffleId: 'Souffle ID',
        approve: 'Approve',
        reject: 'Reject',
      },

      // ----------- Settings -----------
      settings: {
        audio: {
          title: "Immersive Audio Experience",
          subtitle: "Adaptive, spatial, and contextual sounds for total immersion",
          enable: "Enable audio experience",
          volume: "Main Volume",
          theme: "Soundscape",
          immersiveFeatures: "Immersive Features",
          spatial: "Spatial Audio",
          adaptive: "Adaptive Volume",
          contextual: "Contextual Sounds",
          statusActive: "Immersive experience active",
          statusPaused: "Ambiance paused",
          description: "The immersive audio experience automatically adapts to your actions: proximity sounds when approaching a breath, a gentle ambiance during composition, and spatial effects in echo places.",
        },
        personalizeJourney: 'Personalize your contemplative journey',
        appLanguage: 'Application Language',
        languageSubtitle: 'The language in which your world breathes',
        languageDefault: 'English (default)',
        visualMode: 'Visual Mode',
        visualSubtitle: 'Is your gaze made of light or black ink?',
        enableNightMode: 'Enable night mode',
        adaptToDaylight: 'Adapt to daylight cycle',
        visualModeNote: '🌙 Visual mode will be applied on the next app restart',
        breathRadius: 'Breath Radius',
        radiusSubtitle: 'At what distance do you want the wind to hear you?',
        privacy: 'Privacy & Moderation',
        privacySubtitle: 'A safe space for every breath to flourish',
        hideExactLocation: 'Hide my exact location',
        moderatedReading: 'Moderated reading of sensitive breaths',
        participateModeration: 'Participate in citizen moderation',
        notifications: 'Notifications',
        notificationsSubtitle: 'Should an echo let you know?',
        notifyWhenRead: 'Notify me when a breath is read',
        notifyNearby: 'Notify me of new nearby breaths',
        onlyWhenMoving: 'Only when I\'m moving',
        personalHistory: 'Personal History',
        historySubtitle: 'The traces you choose to keep',
        saveDrafts: 'Keep undeposited drafts',
        keepHistory: 'See places where I breathed (7 days)',
        clearTraces: 'Clear my traces',
        aboutUs: 'About Us',
        aboutSubtitle: 'Who are we? Why this wind?',
        readManifesto: 'Read the manifesto',
        openSource: 'Open-source project',
        contactModeration: 'Contact & moderation',
        version: 'Version {{version}}',
        resetPreferences: 'Clear local preferences',
        account: 'Account',
        accountInfo: 'Your account information',
        createAccountPrompt: 'Create an account to save your preferences',
        contact: 'Contact:',
        pseudo: 'Username:',
        memberSince: 'Member since:',
        logout: 'Log out',
        logoutConfirm: 'Are you sure you want to log out?',
        createAccount: 'Create Account',
        alreadyHaveAccount: 'I already have an account',
        anonymousText: 'You are using Silagora in anonymous contemplative mode. Create an account to:',
        anonymousFeature1: '• Save your preferences',
        anonymousFeature2: '• Sync between devices',
        anonymousFeature3: '• Access premium ornaments',
        anonymousFeature4: '• Participate in benevolent moderation',
        discoverShop: 'Discover the shop',
        resetSettingsTitle: 'Start with a clean slate',
        resetSettingsMessage: 'This will erase all your settings and preferences. This action is irreversible.',
        settingsCleared: 'Settings cleared',
        settingsClearedMessage: 'All your settings have been reset to default.',
        clearTracesTitle: 'Clear my traces',
        clearTracesMessage: 'This will permanently delete all your breaths and local history.',
        tracesCleared: 'Traces cleared',
        tracesClearedMessage: 'Your local history has been deleted.',
        citizenModerationTitle: 'Citizen moderation',
        citizenModerationIntro: 'Citizen moderation allows the community to maintain a benevolent and respectful space.',
        howItWorksColon: 'How it works:',
        moderationPoint1: '• Every authenticated member can report an inappropriate breath.',
        moderationPoint2: '• The reported breath is temporarily hidden and submitted to AI for initial analysis.',
        moderationPoint3: '• If AI confirms a problem, the breath is submitted for review by a panel of citizen moderators.',
        moderationPoint4: '• A breath is permanently hidden after a certain number of reports or validation by moderators.',
        moderationCriteriaColon: 'Moderation criteria:',
        criteriaPoint1: '• No hateful, discriminatory, or violent content.',
        criteriaPoint2: '• No harassment, intimidation, or threats.',
        criteriaPoint3: '• No advertising, spam, or promotional content.',
        criteriaPoint4: '• No disclosure of personal information (phone, email, address, etc.).',
        moderationParticipationNote: 'Your participation is voluntary and contributes to a safer space for everyone.',
        understood: 'Understood',
        shop: 'Shop',
      },

      // ----------- About -----------
      about: {
        title: 'About Silagora',
        etymology: 'from latin "silere" (to be silent) and greek "agora" (public square)',
        description: 'A sensitive map of anonymous, free, and geolocated human expression.',
        philosophy: {
          title: 'Our Philosophy',
          text1: 'In a world saturated with digital noise, Silagora offers a space for silence and contemplation. Each deposited breath is an ephemeral trace, a whisper in space and time.',
          text2: 'We believe in the beauty of anonymity, the poetry of the temporary, and the magic of serendipitous encounters.',
        },
        howItWorks: {
          title: 'How It Works',
          step1: { title: 'Compose a Breath', text: 'Write a short message (max 280 characters) and gently deposit it at your current location. Add an ornament to enrich your expression.' },
          step2: { title: 'Explore the Watercolor Map', text: 'Discover the translucent halos floating around you. Each bubble hides a breath left by another traveler.' },
          step3: { title: 'Reveal Breaths', text: 'Physically approach a halo (within a 15-meter radius) to reveal the message it contains.' },
        },
        ephemeral: {
          title: 'The Art of the Ephemeral',
          text1: 'Each breath has a limited lifespan: 24 or 48 hours. After this time, it naturally evaporates, making way for new whispers.',
          text2: 'This temporality encourages spontaneity and preserves the freshness of each discovery.',
        },
        echoPlaces: {
          title: 'Echo Places',
          text: 'When several breaths intersect at the same location, an Echo Place is born. These special areas become poetic crossroads where voices mingle.',
        },
        ethics: {
          title: 'Our Ethics',
          point1: '• Total anonymity: no profiles, no tracking',
          point1Short: 'Total anonymity',
          point2: '• No likes, shares, or statistics',
          point3: '• Benevolent community moderation',
          point4: '• Respect for privacy and data',
          point5: '• Digital sobriety and contemplative design',
          point5Short: 'Digital sobriety',
        },
        contact: {
          title: 'Contact Us',
          email: 'contact@silagora.app',
          openSource: 'Open-source project',
        },
        quote: {
          text: '"In the silence of the digital agora, each breath becomes a fleeting star guiding wandering souls to unexpected encounters."',
          author: 'The Silagora Team',
        },
        version: 'Version {{version}}',
        hackathonCredit: 'Made with 💙 for the Bolt Hackathon • June 2025',
      },

      // ADDED COMMON SECTION
      common: {
        tooFarToRevealTitle: "Too Far to Reveal",
        tooFarToRevealMessage: "You are {{distance}}m away. To reveal this breath, you need to be closer or use one of your {{ticketCount}} tickets.",
        useOneTicket: "Use 1 Ticket",
        cancel: "Cancel",
        souffleRevealed: "Breath Revealed!",
        ticketsRemaining_one: "{{count}} ticket left.",
        ticketsRemaining_other: "{{count}} tickets left.",
        ticketsExhausted: "No Tickets Left",
        visitShopForMoreTickets: "Visit the shop to get more tickets.",
        functionalityReserved: "Reserved Functionality",
        accountRequiredForDistantReveal: "Distant revealing requires an account to manage your tickets."
      },

      // ----------- Achievements -----------
      achievements: {
        first_souffle: {
          title: 'First Breath',
          description: 'Deposit your first breath',
        },
        explorer: {
          title: 'Explorer',
          description: 'Reveal 10 breaths',
        },
        poet: {
          title: 'Urban Poet',
          description: 'Create 25 breaths',
        },
        wanderer: {
          title: 'Wanderer',
          description: 'Walk 10 km while exploring',
        },
        consistent: {
          title: 'Consistent',
          description: 'Use Silagora for 7 consecutive days',
        },
        social: {
          title: 'Connector',
          description: 'Reveal breaths in 5 different places',
        },
      },

      // ----------- Master Login -----------
      masterLogin: {
        title: 'Master Access',
        subtitle: 'Developer Zone Only',
        error: {
          emptyCode: 'Please enter the master code.',
          incorrectCode: 'Incorrect master code. Access denied.',
          creationFailed: 'Failed to create master account.',
        },
        success: {
          title: 'Master Access Granted',
          message: 'Welcome, Developer! Your master account has been activated with full privileges.',
        },
        instructions: {
          title: 'Developer Authentication',
          text: 'Please enter the provided master code to access advanced development features.',
          hint: 'For the hackathon demo, the code is "DEMO2024".',
        },
        input: {
          label: 'Master Code',
          placeholder: 'Enter code here',
        },
        benefits: {
          title: 'Master Account Benefits',
          item1: '✨ Unlimited access to premium ornaments',
          item2: '🎫 Unlimited reveal tickets',
          item3: '🛡️ Advanced moderation tools',
          item4: '🔧 Access to debugging features',
        },
        security: {
          title: 'Security Note',
          text: 'This access is for development purposes only. Never share the master code in production.',
        },
        button: {
          loading: 'Connecting...',
          text: 'Login as Master',
        },
      },

      // ----------- Complete Profile -----------
      completeProfileTitle: 'Complete Profile',
      completeProfileSubtitle: 'Final step before takeoff',
      error: 'Error',
      pseudoTooShort: 'Pseudo must be at least 2 characters long.',
      profileCompletedTitle: 'Profile Completed!',
      profileCompletedMessage: 'Your profile is now complete. You\'re ready for takeoff!',
      start: 'Start',
      unexpectedError: 'An unexpected error occurred.',
      skipStepTitle: 'Skip this step?',
      skipStepMessage: 'You can finalize your pseudo later in settings. Do you want to continue without a pseudo?',
      stayHere: 'Stay here',
      skip: 'Skip',
      welcomeTitleCompleteProfile: 'Congratulations! 🌸',
      welcomeTextCompleteProfile: 'Your account has been successfully created. Just one more touch to personalize your experience.',
      yourAccount: 'Your Account',
      contactLabel: 'Contact:',
      typeLabel: 'Type:',
      emailType: 'Email',
      phoneType: 'Phone',
      choosePseudoTitle: 'Choose Your Pseudo',
      pseudoDescription: 'Your pseudo is the only visible "identity". Choose it carefully, or leave it blank for more anonymity.',
      pseudoPlaceholder: 'Your pseudo (optional)',
      pseudoHint: 'Max 20 characters. Can be changed later in settings.',
      accountBenefitsTitle: 'With your account, you can:',
      benefitSaveSync: 'Save and sync your preferences across all your devices.',
      benefitPremiumFeatures: 'Access exclusive premium breath ornaments.',
      benefitOfferTickets: 'Offer "suspended tickets" to support the community.',
      benefitModeration: 'Participate in citizen moderation for a benevolent space.',
      ourPromise: 'Our Promise',
      ethicsReminderText: 'We are committed to protecting your privacy and will never share your personal data.',
      finalizingProfile: 'Finalizing...',
      completeProfileButton: 'Complete Profile',
      skipStepButton: 'Skip this step',

      // ----------- Create Account -----------
      createAccount: {
        title: 'Create Account',
        subtitle: 'A new page opens...',
        howToConnect: 'How do you want to connect?',
        emailLabel: 'Your email address',
        phoneLabel: 'Your phone number',
        emailPlaceholder: 'example@domain.com',
        phonePlaceholder: '+1234567890',
        pseudoLabel: 'Your pseudo (optional)',
        pseudoHint: 'If left blank, you will remain completely anonymous. You can choose one later.',
        pseudoPlaceholder: 'Your pseudo',
        authTitle: 'How does authentication work?',
        authText: 'We will send you a one-time code via {{contactType}} to verify your identity. No password, it\'s simpler and more secure.',
        authBenefits: 'This allows us to protect your account and sync your data without ever storing a password.',
        commitmentTitle: 'Our commitment',
        commitment1: '🔒 Data security: Your information is encrypted and protected.',
        commitment2: '👤 Anonymity guaranteed: Your breaths are not linked to your real identity.',
        commitment3: '🌱 Digital sobriety: No ads, no manipulative algorithms.',
        submitButton: 'Create My Account',
        submitButtonLoading: 'Creating account...',
        terms: 'By creating an account, you agree to our Terms of Service and Privacy Policy.',
        errorContactRequired: 'Please enter an email address or phone number.',
      },

      // ----------- Login -----------
      login: {
        title: 'Login',
        subtitle: 'The echo returns...',
        welcomeBack: 'Welcome back!',
        instructions: 'Please enter your contact to receive a login code.',
        connectionMethod: 'How do you want to connect?',
        emailLabel: 'Your email address',
        phoneLabel: 'Your phone number',
        emailPlaceholder: 'example@domain.com',
        phonePlaceholder: '+1234567890',
        howItWorks: 'How it works?',
        step1: '1. You enter your {{contactType}}.',
        phone_number_text: 'phone number',
        step2: '2. We send you a one-time code by email or SMS.',
        step3: '3. You enter this code to log in instantly.',
        needHelp: 'Need help?',
        helpText: 'If you don\'t have an account yet or are experiencing login issues, you can create a new one.',
        createNewAccount: 'Create New Account',
        submitButton: 'Get My Code',
        submitButtonLoading: 'Sending code...',
        errorContactRequired: 'Please enter an email address or phone number.',
      },

      // ----------- Verify OTP -----------
      verifyOtp: {
        title: 'Verification',
        subtitle: 'The whisper of authentication',
        codeSentTitle: 'Code sent!',
        codeSentTo: 'We have sent a verification code to:',
        expiresIn: 'It expires in {{count}} minute(s).',
        errorIncomplete: 'Please enter the complete 6-digit code.',
        errorTitle: 'Incorrect Code',
        errorMessage: 'The code you entered is incorrect or has expired.',
        attemptsRemaining: '{{count}} attempt(s) remaining.',
        resendCode: 'Resend Code',
        resendCodeWait: 'Resend in {{count}}s',
        resendTitle: 'Code Resent',
        resendMessage: 'A new code has been sent.',
        resendError: 'Could not resend code. Please try again later.',
        tipsTitle: 'Tips:',
        tips: '• Check your spam folder. • Make sure your number/email is correct. • Contact support if the problem persists.',
        submitButton: 'Verify Code',
        submitButtonLoading: 'Verifying...',
      },

      // ----------- Welcome (First Launch) -----------
      welcome: {
        feature1: { title: 'Ephemeral breaths', description: 'Leave messages that naturally vanish.' },
        feature2: { title: 'Poetic geolocation', description: 'Each breath is anchored to a specific place.' },
        feature3: { title: 'Benevolent anonymity', description: 'No profiles, no followers, just the essence.' },
        feature4: { title: 'Serendipitous encounters', description: 'Discover traces left by other travelers.' },
        featuresTitle: 'The art of the digital breath',
        ethics3Text: 'No advertising',
        ethics4Text: 'Open source',
        startButton: 'Start the adventure',
        alreadyAccountButton: 'I already have an account',
        developerAccess: 'Developer Access',
        locationModalTitle: 'Enable Location?',
        locationModalText: 'Silagora needs your location to allow you to deposit and discover breaths around you. Your exact location will never be recorded or shared.',
        locationModalButton: 'Yes, enable location',
        locationModalSkip: 'Continue without location',
        locationSuccessTitle: 'Location Enabled!',
        locationSuccessMessage: 'You are ready to explore the world of breaths.',
        locationDeniedTitle: 'Location Disabled',
        locationDeniedMessage: 'Some features will be limited without your location. You can enable it later in your device settings.',
        audioModalTitle: 'Enable Audio Experience?',
        audioModalText: 'Immersive audio enriches your exploration with contextual soundscapes and spatial effects. A poetic immersion without headphones, all around you.',
        audioModalButton: 'Yes, enable audio',
        audioModalSkip: 'Continue without sound',
        audioSuccessTitle: 'Audio Enabled!',
        audioSuccessMessage: 'Dive into Silagora\'s sound world.',
        audioDeniedTitle: 'Audio Disabled',
        audioDeniedMessage: 'The experience will be less immersive without audio. You can enable it anytime in settings.',
      },
    },
  },
};

const availableLanguages = [
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'en', name: 'English', native: 'English' }
];

const LanguageContext = createContext<any>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState('fr');

  useEffect(() => {
    const loadLang = async () => {
      const savedLang = await AsyncStorage.getItem('@souffle:language');
      if (savedLang && ['fr', 'en'].includes(savedLang)) {
        setLanguage(savedLang);
        i18n.changeLanguage(savedLang);
      }
    };
    loadLang();
  }, []);

  useEffect(() => {
    i18n
      .use(initReactI18next)
      .init({
        resources,
        lng: language,
        fallbackLng: 'fr',
        compatibilityJSON: 'v3',
        interpolation: {
          escapeValue: false,
        },
      });
  }, [language]);

  const changeLanguage = async (lang: string) => {
    if (['fr', 'en'].includes(lang)) {
      setLanguage(lang);
      i18n.changeLanguage(lang);
      await AsyncStorage.setItem('@souffle:language', lang);
    }
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: changeLanguage,
      t: i18n.t.bind(i18n),
      currentLanguage: language,
      changeLanguage,
      availableLanguages,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}